version: "3.8"

services:

  ices:
    image: vimagick/ices
    volumes:
      - ./data:/etc/ices
    devices:
      - /dev/snd
    depends_on:
      - icecast
    restart: unless-stopped
  
  icecast:
    image: vimagick/icecast
    ports:
      - "8000:8000"
    restart: unless-stopped
