version: "3.8"
services:
  dnsmasq:
    image: vimagick/dnsmasq
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    volumes:
      - ./data:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
